const harryPotterWords = [
    "אדון",
    "herr",
    "גברת",
    "frau",
    "מספר",
    "nummer",
    "ארבע",
    "vier",
    "תינוק",
    "baby",
    "אחות",
    "Schwester",
    "אנשים",
    "Leute",
    "רחוב",
    "Strasse",
    "צוואר",
    "Hals",
    "בוקר",
    "Morgen",
    "נשיקה",
    "Kuss",
    "שטויות",
    "Unsinn",
    "נורמליים",
    "normal",
    "ילד",
    "Junge",
    "מכונית",
    "Auto",
    "מפה",
    "Karte",
    "מייד",
    "Sofort",
    "חתולה",
    "Katze",
    "מוזרות",
    "komisch",
    "יום",
    "tag",
    "מאוחר יותר",
    "später",
    "מקדחות",
    "Bohrer",
    "איש",
    "Mann",
    "שפם",
    "Schnurrbart",
    "שמן",
    "dick",
    "בלונדינית",
    "blond",
    "מישהו",
    "jemand",
    "סיבה טובה",
    "guter Grund",
    "אפור",
    "grau",
    "רמז",
    "Hinweis",
    "שמים",
    "Himmel",
    "עניבה משעממת",
    "langweilige Krawatte",
    "ינשוף",
    "Eule",
    "שלט",
    "zeichen",
    "שלטים",
    "zeichen",
    "חתולים",
    "Katzen",
    "מפות",
    "Karten",
    "ארוחת הבוקר",
    "הFrühstück",
    "עסוק",
    "beschäftigt",
    "בית",
    "Haus",
    "גדרות",
    "Zäune",
    "תודה",
    "Vielen Dank",
    "אנשים",
    "Leute",
    "יום אחד",
    "einmal",
    "דברים",
    "sachen",
    "מוזרים",
    "Komisch",
    "מסתוריים",
    "mysteriös",
    "מוזרים",
    "komisch",
    "מסתוריות",
    "mysteriös",
    "רזה",
    "dünn",
    "שכנים",
    "Nachbarn",
    "סוד",
    "Geheimnis",
    "פחד",
    "Angst",
    "חיים",
    "Leben",
    "יום שלישי",
    "Dienstag",
    "אפלולי",
    "dunkel",
    "תיק",
    "Aktentasche",
    "לנשק",
    "küssen",
    "טעות אופטית",
    "optische Täuschung",
    "בהה",
    "starrte",
    "בהתה",
    "starrte",
    "חזרה",
    "zurück",
    "שנית",
    "nochmal",
    "סימן",
    "Schild",
    "חניה",
    "Parkplatz",
    "ששאלתם",
    "für die Nachfrage",
    "בעולם",
    "in der Welt",
    "פשוט",
    "einfach",
    "חסר",
    "fehlt",
    "להעמיד פנים",
    "vorgeben",
    "שנים רבות",
    "viele Jahre",
    "מדינה",
    "Land",
    "עבודה",
    "Arbeit",
    "שמונה וחצי",
    "halb neun",
    "נשיקה חפוזה",
    "schneller Kuss",
    "משהו",
    "etwas",
    "הבחין",
    "bemerkte",
    "גדול",
    "groß",
    "ידעו",
    "wusste",
    "בגאווה",
    "stolz",
    "שימושי",
    "nützlich",
    "ראו אותו",
    "sah ihn",
    "כסא התינוקות",
    "Babystuhl",
]